
[font]
size = 20.0
offset.y = 3

[font.normal]
family = "MesloLGM Nerd Font Mono"
style = "Regular"

[font.bold]
family = "MesloLGM Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "MesloLGM Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "MesloLGM Nerd Font Mono"
style = "Italic"

[window]
padding = { x = 3, y = 3 }
option_as_alt = "Both"
decorations = "Full"

[scrolling]
# Due to SmoothScroll.app I need a smaller multiplier, the default is 3
multiplier = 1

[mouse]
hide_when_typing = false

[general]
import = ["~/.config/alacritty/catppuccin-macchiato.toml"]
