#!/bin/sh
set -e

TMP_DIR="/tmp"

if [[ -z $VIRTUAL_ENV ]]; then
    echo "enta error: outside venv."
    exit 1
else
    # Remove generated temp tags file on exit
    trap 'rm -f "$TMP_DIR/$$.tags"' EXIT

    echo "enta: generating tags file..."
    ctags -f"$TMP_DIR/$$.tags" $VIRTUAL_ENV
    mv "$TMP_DIR/$$.tags" "$VIRTUAL_ENV/tags"
    exit 0
fi
