#!/usr/bin/python
"""Wrap `isort` python utility to use it as a vim filter.

There is a vim isort plugin but I want to run `isort` installed
in my python virtualenv.
"""

import os
import subprocess
import sys
import tempfile


def main():
    with tempfile.NamedTemporaryFile(dir=os.getcwd()) as f:
        f.write(sys.stdin.read())
        f.seek(0)
        try:
            with open(os.devnull, 'w') as devnull:
                output = subprocess.check_output(
                    'isort -d %s' % f.name,
                    stderr=devnull,
                    shell=True,
                )
        except subprocess.CalledProcessError:
            # Do nothing if isort is not installed and write
            # everything back to stdout.
            output = f.read()

        sys.stdout.write(output)


if __name__ == '__main__':
    main()
